### PR TITLE
Update config_comments.yml

### PR DESCRIPTION
**Pull request by duhnunes**
• Add **camera_editor_f1_tooltip**

### CODE REVIEW

**Comment by mchorse** [comment]
Hey, thanks! Can you also translate [this](https://github.com/mchorse/aperture/compare/1.3.3...master#diff-3d57282c0d653a961bb75ab5c264c5d2L78-R77) and [this](https://github.com/mchorse/aperture/compare/1.3.3...master#diff-7c88845ae8f8e0f54123ce9e3dfaf823R45)? 🙂

**Comment by duhnunes** [comment]
I think if I edit directly in "patch-1" should I change automatically?
Sorry, I don't know 100% github yet, it's always a new apprentice.

**Comment by mchorse** [comment]
Uh, to be honest, I'm not really sure what do you mean. It looks fine to me. You probably shouldn't use GitHub for editing the files. The most optimal way is to actually clone the git repository onto your computer, edit files there, and then push them back. This way you can also update your repository when I add more code.

However, it is quite complicated, not gonna lie. What you can do any time I update the code, you can delete your fork, and then fork it again. That works too 😅

**Comment by duhnunes** [comment]
I say about the branch that is created when I edit the file. But it seems that if I edit the fork I already have it doesn't create a new branch. I don't know git, so I use the site itself. I add the new stuff and compare it to the original file. It is certainly a longer job.

Thank you for the tips.

**Pull request merged**
