### PR TITLE
Use 2 commands to teleport player in servers, and add the ForgeUpdateCheck 

### PR DESCRIPTION
**Pull request by hedw1gP**
Reported by **Ghost_chu**

Since Essentials removed the native teleporting with *real* position in `/tp` (use `/minecraft:tp` instead).

### CODE REVIEW

**Comment by mchorse** [comment]
@ycwei982, would it be compatible with vanilla or Forge server, though? 🤔

**Comment by hedw1gP** [comment]
It should be working, because I remember there is a `/give` command which can let you use not only `stone` but also `minecraft:stone`...

**Comment by mchorse** [comment]
@ycwei982, it's different. Commands doesn't work that way. 😔

I think you should add a config option for essential servers, and then in that place `if` for the correct command.

**Comment by mchorse** [comment]
Is it still unfinished, or I can already merge? @ycwei982 

Hm... Probably, but might it be that it changed four spaces to tab? 🤔

**Comment by hedw1gP** [comment]
Maybe... yes, ~~because adding config options seemed to be like a hardcore job. If I finished, I will create another PR though.~~

**Update:** I am so glad that I did it! But there is still an issue, in the **GUI Camera Options** I cannot hide both `Use /minecraft:tp` and `Use /tp` in singleplayer, and I am using `Minecraft.getMinecraft().isSingleplayer` which you can see `GuiConfigCameraOptions.java`.

And the reason I replaced `/tppos` with `/minecraft:tp` is: `/tppos` doesn't seem to accept *float* position

**Comment by hedw1gP** [comment]
Just found why my Atom is so addicted to delete thousands of spaces and tabs. There is a Whitespaces package built-in. I gonna disable it and do some force push

**Comment by mchorse** [comment]
@ycwei982 another thing you could try is using `mc.getCurrentServerData()` as used in [here](https://github.com/mchorse/aperture/blob/master/src/main/java/mchorse/aperture/ClientProxy.java#L93-L97), but it's weird that `!isSingleplayer()` triggers in singleplayer...

**Comment by hedw1gP** [comment]
All done! Thanks for your help 😄

**Comment by mchorse** [comment]
Great job, thanks! I'm gonna merge it 🙂 👌

**Pull request merged**
